# Generated by Django 3.2.9 on 2021-12-31 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_users_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='profile_pic',
        ),
    ]
