# Generated by Django 3.2.9 on 2021-12-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_users_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='images'),
        ),
    ]
